esphome:
  name: $devicename

esp8266:
  board: esp12e

# Enable logging
logger:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dev Fallback Hotspot"
    password: !secret wifi_fallback_ap_password

web_server:
  port: 80

captive_portal:

deep_sleep:
  id: deep_sleep_1
  run_duration: 1s
  sleep_duration: 59s

mqtt:
  broker: mqtt.tomlins.org.uk
  birth_message:
  will_message:
  on_message:
    - topic: $devicename/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: $devicename/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1

dallas:
  - pin: 13
