esphome:
  name: $devicename

esp8266:
  board: esp12e

# Enable logging
logger:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dev Fallback Hotspot"
    password: !secret wifi_fallback_ap_password

web_server:
  port: 80

captive_portal:

mqtt:
  broker: 10.10.10.1
  discovery: false

dallas:
  - pin: 13

sensor:
  - platform: dallas
    index: 0
    name: "Dev Temperature"
    accuracy_decimals: 3
